### ISSUE TITLE
Improve performance of getAllTransactionsForAccount

### ISSUE THREAD

**Issue by MarceloPrado** [pluggyai/pluggy-node#93]
There's an opportunity to improve the performance of the `getAllTransactionsForAccount` method. Pluggy defaults to `20` items per `pageSize`. Looking at the [implementation](https://github.com/pluggyai/pluggy-node/blob/4ec566d5b7feefcf08920667d4dfd20fca8c26c1/src/client.ts#LL181C12-L181C12), it seems the SDK recursively calls `fetchTransactions` until there are no more pages.

The issue with the existing implementation is that it's not updating the `pageSize`. By keeping the default of 20 items, we incur extra latency costs for each request. If we updated to use the maximum of `500`, there would be fewer requests to Pluggy's back-end. 

It's worth saying the bandwidth costs would increase, given the payload would grow from 20 transactions to up to 500. However, given the implementation requires requests to execute serially, I believe optimizing to fewer and larger responses would improve response time.

**Comment by NicolasMontone** [comment]
Thanks for the comment @MarceloPrado! We will add the improvement!
