### ISSUE TITLE
Missing nextAutoSyncAt in Item

### ISSUE THREAD

**Issue by MarceloPrado** [pluggyai/pluggy-node#95]
Hi!
It seems the `Item` [type definition](https://github.com/pluggyai/pluggy-node/blob/master/src/types/item.ts#L61-L90) is missing the `nextAutoSyncAt` param.

**Comment by tmilar** [comment]
Hi @MarceloPrado ! 
Thanks for pointing that out. We've just added this in https://github.com/pluggyai/pluggy-node/pull/96, and is now available in the latest release.
